WITH CATEGORYMETRICS AS (
    SELECT
        OFFENSE_CATEGORY,
        CASE
            WHEN PERCENT_LESS_THAN_50K <= 0.10 THEN '0-10%'
            WHEN PERCENT_LESS_THAN_50K <= 0.20 THEN '11-20%'
            WHEN PERCENT_LESS_THAN_50K <= 0.30 THEN '21-30%'
            WHEN PERCENT_LESS_THAN_50K <= 0.40 THEN '31-40%'
            WHEN PERCENT_LESS_THAN_50K <= 0.50 THEN '41-50%'
            ELSE 'Over 50%'
        END AS PERCENT_OF_COMMUNITY_MAKING_LESS_THAN_50K,
        COUNT(*) AS TOTAL_CRIMES,
        ROUND(
            (COUNT(*) - SUM(CASE WHEN ARREST THEN 1 ELSE 0 END))
            / COUNT(*)
            * 100,
            2
        ) AS UNSOLVED_PERCENTAGE
    FROM `chicago_justice.crime_analysis_by_community`
    GROUP BY PERCENT_OF_COMMUNITY_MAKING_LESS_THAN_50K, OFFENSE_CATEGORY
),

RANKEDMETRICS AS (
    SELECT
        *,
        RANK()
            OVER (
                PARTITION BY PERCENT_OF_COMMUNITY_MAKING_LESS_THAN_50K
                ORDER BY TOTAL_CRIMES DESC
            )
            AS VOLUME_RANK,
        RANK()
            OVER (
                PARTITION BY PERCENT_OF_COMMUNITY_MAKING_LESS_THAN_50K
                ORDER BY UNSOLVED_PERCENTAGE DESC
            )
            AS UNSOLVED_RANK
    FROM CATEGORYMETRICS
)

SELECT
    PERCENT_OF_COMMUNITY_MAKING_LESS_THAN_50K,
    OFFENSE_CATEGORY,
    TOTAL_CRIMES,
    UNSOLVED_PERCENTAGE,
    CASE
        WHEN
            VOLUME_RANK <= 2 AND UNSOLVED_RANK <= 2
            THEN 'Top Volume & Top Unsolved'
        WHEN VOLUME_RANK <= 2 THEN 'Top Volume'
        WHEN UNSOLVED_RANK <= 2 THEN 'Top Unsolved'
    END AS INSIGHT_LABEL
FROM RANKEDMETRICS
WHERE VOLUME_RANK <= 2 OR UNSOLVED_RANK <= 2
ORDER BY UNSOLVED_PERCENTAGE DESC;
